name: ci

on:
  push:
    branches: 
    - '**' 

jobs:
  build:
    name: build pluscal
    runs-on: ubuntu-latest
    container:
      image: talex5/tla
    steps:
    - uses: actions/checkout@v2
    - run: find *.tla | xargs pcal

  model-checking:
    name: test model
    runs-on: ubuntu-latest
    container:
      image: talex5/tla
    steps:
    - uses: actions/checkout@v2
    - run: find *.tla | xargs tlc

  lint:
    name: lint
    runs-on: ubuntu-latest
    container:
      image: talex5/tla
    steps:
    - uses: actions/checkout@v2      
    - run: find *.tla | xargs tlc -syntaxCheck