name: ci

on:
  push:
    branches: 
    - '**' 

jobs:
  build:
    name: build pluscal
    runs-on: ubuntu-latest
    container:
      image: talex5/tla
    defaults:
        run:
           working-directory: /
    steps:
    - uses: actions/checkout@v4
    - run: pwd
    - run: ls ../
    - run: ls ../../
    - run: ls -a
    - run: find *.tla | xargs java -cp tla2tools.jar pcal.trans
  test:
    name: test model
    runs-on: ubuntu-latest
    container:
      image: talex5/tla
    steps:
    - uses: actions/checkout@v4
    - run: find *.tla | xargs java -cp tla2tools.jar tlc2.TLC
  lint:
    name: lint
    runs-on: ubuntu-latest
    container:
      image: talex5/tla
    steps:
    - run: echo "The absence of an official formatter in TLA+ prevents verifying the format."