name: ci

on:
  push:
    branches: 
    - '**' 

jobs:
  build:
    name: build pluscal
    runs-on: ubuntu-latest
    container:
      image: hackenfreude/tlatoolbox-1.5.2
    steps:
    - uses: actions/checkout@v2
    - name: Run TLA+ model checking
      run: tlc path/to/your/tla_file.tla
    - run: pwd
    - run: ls ../
    - run: ls ../../
    - run: ls -a
    - run: find *.tla | xargs pcal

  model-checking:
    name: test model
    runs-on: ubuntu-latest
    container:
      image: hackenfreude/tlatoolbox-1.5.2
    steps:
    - uses: actions/checkout@v2
    - name: Run TLA+ model checking
      run: tlc path/to/your/tla_file.tla    
    - run: find *.tla | xargs tlc
  lint:
    name: lint
    runs-on: ubuntu-latest
    container:
      image: hackenfreude/tlatoolbox-1.5.2
    steps:
    - name: Validate TLA+ syntax
      run: find *.tla | xargs tlc -syntaxCheck